### ISSUE TITLE
Can't access secrets repo

### ISSUE THREAD

**Issue by jdmar3** [comp426-2022-spring/general-info#1]
A lot of students don't have access to the secrets repo. WTF

**Comment by bvalient** [comment]
That's rough

**Comment by christineiym** [comment]
We need to be added to the organization.

**Comment by gabomm99** [comment]
I can see this, but not the secrets.

**Comment by andymking** [comment]
Hello there

**Comment by eohana-unc** [comment]
You have to be in the class

**Comment by cgoldman123** [comment]
Oh word?

**Comment by franqfzh** [comment]
Hey

**Comment by ravent61** [comment]
me neither!

**Comment by sningle** [comment]
rip secrets :(

**Comment by erayala15** [comment]
sheeeeee

**Comment by elaine331917** [comment]
Hello

**Comment by jcsansom-cyber** [comment]
Nice

**Comment by AndrewByerle** [comment]
facts

**Comment by Peiyu-Li-Tara** [comment]
neither

**Comment by RJudge1170** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

**Comment by Xixiang-Liu** [comment]
try to make a comment

**Comment by wenbo68** [comment]
I know right. WTF

**Comment by NeilVakharia45** [comment]
tuff

**Comment by ZackBarbari** [comment]
Bababooey

**Comment by carohamunc** [comment]
hello

**Comment by Nina2023** [comment]
hi

**Comment by guisaez** [comment]
Hello

**Comment by avmad22** [comment]
hi

**Comment by poojha-p** [comment]
present

**Comment by jdmar3** [comment]
So, like @christineiym said above, it looks like once your account is added to the org, you will have access to the secrets. BUT, GitHub cut us off because we invited a bunch of ourselves all at once and they found this to be very suspicious behavior indeed. See issue #3 for details.
