### ISSUE TITLE
Cannot access secrets repo, despite being member of comp426-2022-spring organization

### ISSUE THREAD

**Issue by christineiym** [comp426-2022-spring/general-info#10]
Despite being a member of the organization since a few hours ago, I and a couple other classmates (Harin Kim, Gillian Zech -- I would tag them, but I do not have permissions to do so) still cannot access the secrets repo. We receive a "Page not found" error.

![image](https://user-images.githubusercontent.com/69741280/149597167-6683d8b6-a1be-43ee-b290-a88aaf4982b1.png)

Has the link to it/permissions changed, or is this another case of GitHub needing some time to process our new permissions?

I also cannot assign labels, assignees, etc, nor can I reopen issues (though the latter issue seems to be [a common one](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github)) -- hence the new issue pertaining to #1  (and #6) .

Thanks for your time throughout all of these set-up difficulties!

**Comment by camsimba** [comment]
I believe this has to do with who is currently allowed access to it. It seems that there are currently 0 members and 0 teams allowed to access it. I'll check with John and see if we can change this without major issue. If anyone is able to access the secrets repo, please let me know!

**Comment by jdmar3** [comment]
This should be fixed now. I have added all members to the repo for read access. The TAs have maintain access.

**Comment by christineiym** [comment]
Thank you so much -- I can access it now!
