### ISSUE TITLE
MDH enrollment link does not work

### ISSUE THREAD

**Issue by christineiym** [comp426-2022-spring/general-info#11]
Unfortunately, clicking on the enrollment link/entering the url (https://mydigitalhand.org/enrollment/30895) in the browser gives me and @ Gillian Zech this page for forever:

![image](https://user-images.githubusercontent.com/69741280/149598015-8b563241-32d7-49b1-ae15-f48d898607b0.png)

There's nothing logged to the browser console, so I'm not sure what is the issue.

I have also tried enrolling by simply searching for the class, but I do not have a valid entry code:
![image](https://user-images.githubusercontent.com/69741280/149598164-449ca29b-5b08-470d-ab3e-bfdfba4e8417.png)

Would it be possible for us to obtain an entry code for the course? Thank you!

**Comment by jdmar3** [comment]
You should be able to access the enrollment code at https://github.com/comp426-2022-spring/secrets. I think that I have fixed the access problem to the SECRETS repo identified in #10. I am able to access it now with my student account. Confirm?

**Comment by christineiym** [comment]
Thank you so much! Confirmed that I can access it and that the enrollment code works! I did manually search up the course instead of using the link due to the stuck loading page, and I had to wait a couple of minutes for an email from confirm@mydigitalhand.org to show up in my Spam folder so I could confirm my email address, but I was able to enroll in the course.
