### ISSUE TITLE
TAs add office hours to general-info README.md

### ISSUE THREAD

**Issue by jdmar3** [comp426-2022-spring/general-info#12]
For TAs and LAs assigned to this issue, please add office hours to https://github.com/comp426-2022-spring/general-info/.

**Comment by jdmar3** [comment]
@smelliskay first office hours pull request winner!

**Comment by jdmar3** [comment]
Two more! Thank you, @oizokun and @samrshi! Come on everyone else and join us!

**Comment by jdmar3** [comment]
All the ULAs have set office hours! It would be great if the grad TAs @camsimba and @md-mohaiminul could cover a couple of hours on days when we don't have a lot of coverage (provided that it works with your existing schedules). 

Wednesday and Friday before 1pm is needed if at all possible as is Monday anytime during the day before 4pm.

Tuesday and Thursday: I think we're good.

**Comment by camsimba** [comment]
Sorry, this week has been a little hectic. I'll set up some office hours on Monday and Wednesday.

**Comment by jdmar3** [comment]
Awesome. thank you. I've integrated them.
