### ISSUE TITLE
Downloading programs help

### ISSUE THREAD

**Issue by GillianZech** [comp426-2022-spring/general-info#17]
Posted this in the a00 issues but wanted to post it here to just in case.
We downloaded similar programs for comp211 and other comp classes, so I'm having trouble figuring out which stuff I already have and which stuff I still need. For the things I know I need, I can't seem to download them because I keep getting told "command not found" when I use "sudo."

**Comment by jdmar3** [comment]
I've marked this as a duplicate since we're already triaging your issue on a00.
