### ISSUE TITLE
which command does not work

### ISSUE THREAD

**Issue by poojha-p** [comp426-2022-spring/general-info#22]
If I try running the which command on my terminal, I get this error:

`which : The term 'which' is not recognized as the 
name of a cmdlet, function, script file, or         
operable program. Check the spelling of the name,   
or if a path was included, verify that the path is  
correct and try again.`

**Comment by camsimba** [comment]
Hi, I'll see if I can help some. Are you trying to use `which` in Windows Powershell or CMD? `which` is a Bash command, so other Command Line Interfaces (CLIs) that don't use Bash won't be able to use the command. If you are using Windows, you would need to install the Windows Subsystem for Linux as listed in the assignment write-up (I think it's installation number 4 at the top of the setup page). https://comp426.johndmart.in/a/00/

Let me know if this doesn't help and we can dive a little deeper into it!

**Comment by poojha-p** [comment]
I installed WSL and restarted my computer, but am still unable to run the which command in Powershell or in my VSCode terminal. If I look up the WSL command on my start menu and try to open it, nothing happens. Same when I type the wsl command in my cmd prompt.

**Comment by jdmar3** [comment]
When you open the VSCode terminal, which terminal is it opening. It should show you in the corner of the terminal pane which shell is running: 

![image](https://user-images.githubusercontent.com/2459227/151019529-d07d620f-c001-4058-915d-4725b628da56.png)

If it is not using `bash` by default, then you can change it in the settings. Search the settings for "terminal default profile" and set the one for Linux to "bash."

See this also: 

https://code.visualstudio.com/docs/remote/wsl#_opening-a-terminal-in-wsl

**Comment by poojha-p** [comment]
Thank you! This really helped.
