### ISSUE TITLE
Github extensions not working on VS Code

### ISSUE THREAD

**Issue by kenxh** [comp426-2022-spring/general-info#23]
When I go to VS Code my github tab doesn't render anything, so I can't see the tests or assignments or essentially anything related to github. I was able to push and commit but for a while the autograder bot kept committing throughout the night but it seemed to have stopped. I have tried uninstalling, disabling & reenabling the extensions, and restarting my computer but it has not worked. Here is what it currently looks like:

![image](https://user-images.githubusercontent.com/69732946/151405648-2bdabcfe-062b-4ab8-9afd-87521a167180.png)

**Comment by jdmar3** [comment]
Hrmm. That might need some triage.

Can you confirm that you are logged into GitHub on VSCode via accounts?

Can you use the terminal to interact with git and GitHub?

I'm wondering if maybe there is a problem with git being installed or an extension or something.

**Comment by kenxh** [comment]
I believe I am logged in and the terminal recognizes my git commands.

![image](https://user-images.githubusercontent.com/69732946/151410220-0f3050e6-389f-4d16-8a95-87aa28cab04b.png)

![image](https://user-images.githubusercontent.com/69732946/151410241-c7d84420-7362-414c-9ae3-842929f4d26c.png)

**Comment by kenxh** [comment]
Ok so I completely logged out of github on VS Code and all of the accompanying extensions and then logged back in and when I logged back into each extension it reloaded. Hopefully I won't have anymore issues!
