### ISSUE TITLE
Git not working correctly

### ISSUE THREAD

**Issue by kenxh** [comp426-2022-spring/general-info#26]
Tried to push my changes and it gave me this: 
![image](https://user-images.githubusercontent.com/69732946/152926008-422b00d1-5643-405c-bbb0-cf6d7d965847.png)

I tried logging in and out of Github and even deleting my credentials from Windows Credentials with the hope of reentering in my credentials but I continue to get this same error except now my git credentials are not even in Windows Credentials. Don't really understand what's going wrong and I don't want to do anything else in order to prevent anything from getting worse.

**Comment by aakash-comp** [comment]
Hey, was wondering exactly how you went through fixing this error. I am having the same problems
