### ISSUE TITLE
Was note placed in a group 

### ISSUE THREAD

**Issue by sshi26** [comp426-2022-spring/general-info#27]
I don't believe I was placed in a group for the group project. Was I supposed to do something to be placed in a group? Thank you!

**Comment by Peter-H-Jackson** [comment]
I was also not placed into a group. Please let me know what needs to be done on my side to have that happen!

**Comment by camsimba** [comment]
I'll bring this to John's attention

**Comment by jdmar3** [comment]
So the data source that I used to generate the team assignments is the beginning questionnaire, which is listed on the secrets repo because it is not available to the general public. Have you filled that out? If not, do so. In the meantime, I will work on adding you both to existing teams as well.

**Comment by Peter-H-Jackson** [comment]
I thought I filled it out but I guess I did not. Just filled it out! Sorry for the inconvenience.

**Comment by sshi26** [comment]
Same here! I also forgot to fill out the questionnaire, but it's filled out now!

**Comment by jdmar3** [comment]
Awesome. 

@sshi26, you are in this team: https://github.com/orgs/comp426-2022-spring/teams/mizar/

@Peter-H-Jackson, you are in this team now: https://github.com/orgs/comp426-2022-spring/teams/vega/
