### ISSUE TITLE
2/8 Lecture Recording not on Panopto 

### ISSUE THREAD

**Issue by vlalithaunc** [comp426-2022-spring/general-info#28]
I was unable to attend Tuesday's lecture synchronously and I was wondering when the recorded lecture will be uploaded onto Panopto. Thanks!

**Comment by jdmar3** [comment]
Ah yes. It will be up shortly. I just have to edit it down since we mostly did a team interaction session on Tuesday. I will transfer Tuesday's lecture and yesterday's over today.

**Comment by jdmar3** [comment]
Both of last week's recordings are up now. They required a little extra editing and I forgot that I had flagged them not to move automatically over to Panopto.
