### ISSUE TITLE
MyDigitalHand Verification

### ISSUE THREAD

**Issue by fdahnoun** [comp426-2022-spring/general-info#29]
I was trying to join the course for myDigitalHand but it said I needed to verify my email. However, I never received this email to verify. Is there any way someone could verify me manually?

Thank you

-Ferras Dahnoun

**Comment by sadye** [comment]
I have the same issue. I have tried using @live.unc.edu, @email.unc.edu and @unc.edu after my onyen and none will send the email

**Comment by jdmar3** [comment]
I just changed MDH settings to not require email confirmation, but you will still need the passcode, which is in https://github.com/comp426-2022-spring/secrets

Let me know if you still have trouble getting in.

**Comment by jdmar3** [comment]
I'm going to go ahead and close this issue. You can reopen it if you are still having trouble with MDH.

**Comment by fdahnoun** [comment]
Sorry for the late response. It works now thank you.
