### ISSUE TITLE
My Digital hand raising

### ISSUE THREAD

**Issue by sadye** [comp426-2022-spring/general-info#31]
My MDH is not responding. When I submit the Get Help Now questionnaire,my  hand stays down and when I click Get Help now again it shows my previous answers. I also tried to update my tagline and my profile pictures, and none of that updated. Is there any tips for this.

**Comment by jdmar3** [comment]
Huh. This is new to me. I haven't seen that happen with MDH before. I'll poke around at the settings and see if there is anything that seems amiss.

**Comment by sadye** [comment]
It worked today -- but was a really weird bug yesterday and the day before

**Comment by jdmar3** [comment]
Oh strange. So, I am in MDH until about 17:45 today if you still need help today. I saw that you were still on the waitlist from earlier and sent a Zoom link.
