### ISSUE TITLE
npm init a00 error

### ISSUE THREAD

**Issue by ibraheemsag2** [comp426-2022-spring/general-info#37]
I get the error "/usr/bin/env: ‘bash\r’: No such file or directory" when I run npm init. I have gotten this error on three separate devices after following the installation process on the website.

**Comment by ibraheemsag2** [comment]
![Capture](https://user-images.githubusercontent.com/54514706/157749180-a8614a8d-256a-448a-bd7e-0b255be25491.PNG)

**Comment by jdmar3** [comment]
I'm not sure quite what is going on here and I'm sorry that I let the issue languish from before spring break.

Do you have some time Friday of this week to get on Zoom and I can try to help diagnose the problem?

**Comment by ibraheemsag2** [comment]
I ended up fixing it. I deleted everything and did it on ubuntu instead of debian.
