### ISSUE TITLE
Not currently a team member for a99

### ISSUE THREAD

**Issue by turner-white** [comp426-2022-spring/general-info#39]
After the class announcement today I discovered the teams section of github for the first time and saw that I am not part of a team yet (which explains why I haven't been receiving/responding to any messages). I'm sorry that I haven't noticed this sooner, but I'm hoping to join a team and wanted to let someone know that I don't have one right now. Thanks!

**Comment by zfbxrk518** [comment]
Hi all! I'm sorry I found myself was not in any team yet so I can't contact with my team members to discuss the final project. Does a team look for a team member?

**Comment by acpaulsen** [comment]
I'm also having a similar issue it seems?

**Comment by jdmar3** [comment]
Hi everyone. I think I have enough members for a new team now so I am going to create one. Watch this space and I'll let you know when it is done.

**Comment by jdmar3** [comment]
Also need to add following members to teams: 

@Fred-Ji112

**Comment by jdmar3** [comment]
Added to @comp426-2022-spring/mira
@turner-white

Added to @comp426-2022-spring/izar 
@zfbxrk518

Added to @comp426-2022-spring/pollux 
@Fred-Ji112

Added to @comp426-2022-spring/rigel 
@hmumixaM
@rkjain02

Added to @comp426-2022-spring/rotanev 
@colehenry

Added to @comp426-2022-spring/taygeta 
@acpaulsen
