### ISSUE TITLE
Final Project Team not assigned 

### ISSUE THREAD

**Issue by hmumixaM** [comp426-2022-spring/general-info#40]
Dear Dr. Martin, I am not in any team for the final project. Could you add me into a team for the project?
<img width="1052" alt="Screen Shot 2022-02-17 at 20 25 26" src="https://user-images.githubusercontent.com/25889636/154600185-8a9ee022-16b5-4ae6-ac53-3a0489395836.png">

**Comment by jdmar3** [comment]
I am going to merge this issue into #39 so that I can keep everything related to unassigned teams organized there.
